# Generated by Django 4.2.1 on 2023-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('clase', models.CharField(max_length=100)),
                ('especializacion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='personajes/')),
                ('imagen3d', models.FileField(blank=True, upload_to='personajes/')),
            ],
        ),
    ]
