# Generated by Django 4.2.1 on 2023-06-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='imagen3d',
            field=models.FileField(blank=True, upload_to='personajes/'),
        ),
    ]
