# Generated by Django 4.2.1 on 2023-07-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especializacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ref_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.clase')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('caracteristicas', models.CharField(max_length=400)),
                ('precio', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('imagen', models.FileField(upload_to='productos/')),
                ('ref_especializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.especializacion')),
                ('ref_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.estadoproducto')),
            ],
        ),
    ]
