# Generated by Django 4.2.1 on 2023-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dañofisico',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='producto',
            name='dañomagico',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='producto',
            name='dps',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='ilevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='nivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stadistica1',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='stadistica2',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='vataque',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
